apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: lapras
servers: 1
agents: 0
network: lapras
image: rancher/k3s:v1.27.4-k3s1
ports:
  - port: 10110:80
    nodeFilters:
      - loadbalancer
  - port: 10111:443
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: lapras.registry.lvh.me
    host: "0.0.0.0"
    hostPort: "10112"
