apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubefwd-labeler.fullname-with-suffix" (dict "arg" "config" "root" .) }}
  labels: {{- include "kubefwd-labeler.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
data:
  services.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
