apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-labeler"
  labels: {{- include "kubefwd-labeler.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["update","get","patch","list"]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get","list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-labeler"
  labels: {{- include "kubefwd-labeler.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubefwd-labeler.serviceAccountName" . }}
    namespace: "{{.Release.Namespace}}"
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-labeler"
  apiGroup: rbac.authorization.k8s.io
