apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubefwd-labeler.serviceAccountName" . }}
  labels: {{- include "kubefwd-labeler.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.annotations | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
